version: "3.9"

services:
  web:
    container_name: frontendpasswordpoc
    build: .
    volumes:
      - '.:/app/src'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install --force && npm start"